### ISSUE TITLE
Failed to build on Windows (exit code: 101)

### ISSUE THREAD

**Issue by sabtorres** [google/shaderc-rs#42] opened 2019-03-03 23:13 UTC
shaderc fails to build on windows
latest version, rust version 1.33.0, cargo version 1.33.0
all the pre-requisites to build are in the system
I couldn't deduce anything useful from the stderr output. If someone can, that'd be great.

this is the entire error output:

`Compiling` shaderc v0.3.16
error: failed to run custom build command for `shaderc v0.3.16`
process didn't exit successfully: `C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-7c36252434f41bda\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\guilh\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\shaderc-0.3.16\\build" "-G" "Visual Studio 15 2017 Win64" "-Thost=x64" "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DSPIRV_SKIP_EXECUTABLES=ON" "-DSPIRV_WERROR=OFF" "-DSHADERC_SKIP_TESTS=ON" "-DCMAKE_C_FLAGS= /nologo /EHsc" "-DCMAKE_CXX_FLAGS= /nologo /EHsc" "-DCMAKE_C_FLAGS_RELEASE= /nologo /EHsc" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /EHsc" "-DCMAKE_INSTALL_LIBDIR=lib" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\guilh\\github\\KitsuneEngine2\\target\\debug\\build\\shaderc-a487fde340fded54\\out" "-DCMAKE_BUILD_TYPE=Release"
-- Building SPIRV-Header examples
-- SPIRV-Tools: nosetests was not found - python support code will not be tested
-- Using Debug VC++ CRT: MDd
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Google Mock was not found - tests based on that will not build
-- optimizer enabled
-- Shaderc: build type is "Release".
-- Configuring Shaderc to avoid building tests.
-- nosetests was not found - python code will not be tested
-- asciidoctor was not found - no documentation will be generated
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/guilh/github/KitsuneEngine2/target/debug/build/shaderc-a487fde340fded54/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  HLSL.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\hlsl\Release\HLSL.lib
  OGLCompiler.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\OGLCompilersDLL\Release\OGLCompiler.lib
  OSDependent.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\glslang\OSDependent\Windows\Release\OSDependent.lib
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "x64\Release\spirv-tools-spv-amd-shader-explicit-vertex-parameter\spirv-to.2E826A11.tlog\spirv-tools-spv-amd-shader-explicit-vertex-parameter.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\spirv-tools\source\spirv-tools-spv-amd-shader-explicit-vertex-parameter.vcxproj]
  glslang.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\glslang\Release\glslang.lib
  SPIRV-Headers-example.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\spirv-headers\example\Release\SPIRV-Headers-example.lib
  SPIRV-Headers-example-1.1.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\spirv-headers\example\Release\SPIRV-Headers-example-1.1.lib
  SPVRemapper.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\SPIRV\Release\SPVRemapper.lib
  Check copyright
  glslang-default-resource-limits.vcxproj -> C:\Users\guilh\github\KitsuneEngine2\target\debug\build\shaderc-a487fde340fded54\out\build\glslang\StandAlone\Release\glslang-default-resource-limits.lib
  Update build-version.inc in the Shaderc build directory (if necessary).

--- stderr
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\guilh\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.35\src\lib.rs:778:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Comment by antiagainst** [comment] 2019-03-04 00:38
This is a duplicate of https://github.com/google/shaderc-rs/issues/33. Please see the discussion there. :)

**Closed as completed by antiagainst** 2019-03-04 00:38 UTC

**Comment by sabtorres** [comment] 2019-03-04 00:47
thanks for the attention

**Comment by antiagainst** [comment] 2019-03-04 01:00
No worries! It's an annoying issue that I don't have a nice solution yet. So it's mainly workaround for now. Sorry about that!
